# Generated by Django 6.0 on 2025-12-28 02:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("players", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Mail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100, verbose_name="邮件标题")),
                ("content", models.TextField(verbose_name="邮件内容")),
                (
                    "is_global",
                    models.BooleanField(default=False, verbose_name="全服邮件"),
                ),
                (
                    "item_id",
                    models.IntegerField(blank=True, null=True, verbose_name="道具ID"),
                ),
                (
                    "item_count",
                    models.PositiveIntegerField(default=0, verbose_name="道具数量"),
                ),
                ("expires_at", models.DateTimeField(verbose_name="过期时间")),
                (
                    "is_claimed",
                    models.BooleanField(default=False, verbose_name="已领取"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "receiver",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="received_mails",
                        to="players.player",
                        verbose_name="接收者(玩家)",
                    ),
                ),
                (
                    "sender",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sent_mails",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="发送者(管理员)",
                    ),
                ),
            ],
            options={
                "verbose_name": "邮件",
                "verbose_name_plural": "邮件列表",
                "db_table": "mails",
                "ordering": ["-created_at"],
            },
        ),
    ]
