# Generated by Django 6.0 on 2025-12-31 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mails", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mail",
            name="expires_at",
            field=models.DateTimeField(db_index=True, verbose_name="过期时间"),
        ),
        migrations.AlterField(
            model_name="mail",
            name="is_claimed",
            field=models.BooleanField(
                db_index=True, default=False, verbose_name="已领取"
            ),
        ),
        migrations.AlterField(
            model_name="mail",
            name="is_global",
            field=models.BooleanField(
                db_index=True, default=False, verbose_name="全服邮件"
            ),
        ),
    ]
