"""
Django settings for my_gm_backend project.

Generated by 'django-admin startproject' using Django 6.0.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# 加载 .env 环境变量文件
load_dotenv(BASE_DIR / '.env')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv(
    "SECRET_KEY",
    "django-insecure-3gyv&b^+4a(6-nglro!#+3aut6h3j)l#(28(on^!t_*rkr18ro"  # 开发默认值
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv("DEBUG", "True").lower() in ("true", "1", "yes")

ALLOWED_HOSTS = ["*"]  # 开发环境允许所有主机访问


# ============================================
# 📦 Application definition - 已安装的应用
# ============================================

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    # ===== 第三方应用 =====
    "rest_framework",               # Django REST Framework - 构建 API
    "rest_framework_simplejwt",     # JWT 身份验证
    "corsheaders",                  # 跨域支持
    # ===== 自定义应用 =====
    "players",              # 玩家管理模块
    "mails",                # 邮件补偿模块
    "notices",              # 全服公告模块
    "cdks",                 # 礼包码系统
    "audit",                # 审计日志
]

# ============================================
# 🔗 Middleware - 中间件配置
# ============================================

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",  # ⚠️ 必须放在最前面！
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "my_gm_backend.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "my_gm_backend.wsgi.application"


# ============================================
# 🗄️ Database - 数据库配置 (PostgreSQL)
# ============================================

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": os.getenv("DB_NAME", "gm_system"),
        "USER": os.getenv("DB_USER", "postgres"),
        "PASSWORD": os.getenv("DB_PASSWORD", "123456"),  # 生产环境必须从环境变量读取
        "HOST": os.getenv("DB_HOST", "localhost"),
        "PORT": os.getenv("DB_PORT", "5432"),
    }
}


# ============================================
# 🌐 CORS - 跨域配置
# ============================================

# 开发环境：允许所有来源（生产环境请改为具体域名）
_cors_origins = os.getenv("CORS_ALLOWED_ORIGINS", "")
if _cors_origins:
    CORS_ALLOW_ALL_ORIGINS = False
    CORS_ALLOWED_ORIGINS = [origin.strip() for origin in _cors_origins.split(",")]
else:
    CORS_ALLOW_ALL_ORIGINS = True  # 开发默认


# ============================================
# 🔌 REST Framework - API 配置
# ============================================

REST_FRAMEWORK = {
    # 默认认证方式: JWT
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ],
    # 默认权限: 必须登录 (白名单接口单独设置 AllowAny)
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.IsAuthenticated",
    ],
    # 渲染器: 统一响应格式
    "DEFAULT_RENDERER_CLASSES": [
        "utils.renderers.UnifiedResponseRenderer",  # 统一响应格式
        "rest_framework.renderers.BrowsableAPIRenderer",  # 保留 DRF 浏览界面
    ],
    # 全局异常处理器
    "EXCEPTION_HANDLER": "utils.exception_handler.custom_exception_handler",
}

# ============================================
# 🔐 JWT 配置
# ============================================
from datetime import timedelta

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(hours=24),   # Access Token 有效期: 24小时
    "REFRESH_TOKEN_LIFETIME": timedelta(days=7),    # Refresh Token 有效期: 7天
    "ROTATE_REFRESH_TOKENS": True,                  # 刷新时轮换 Refresh Token
    "BLACKLIST_AFTER_ROTATION": True,               # 轮换后旧 Token 加入黑名单
    "AUTH_HEADER_TYPES": ("Bearer",),               # Header 格式: Bearer <token>
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# ============================================
# 🌍 Internationalization - 国际化配置
# ============================================

LANGUAGE_CODE = "zh-hans"  # 中文简体

TIME_ZONE = "Asia/Shanghai"  # 中国时区

USE_I18N = True

USE_TZ = True


# ============================================
# 📁 Static files - 静态文件
# ============================================

STATIC_URL = "static/"

# Default primary key field type
DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"
