"""
Django settings for my_gm_backend project.

Generated by 'django-admin startproject' using Django 6.0.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-3gyv&b^+4a(6-nglro!#+3aut6h3j)l#(28(on^!t_*rkr18ro"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["*"]  # 开发环境允许所有主机访问


# ============================================
# 📦 Application definition - 已安装的应用
# ============================================

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    # ===== 第三方应用 =====
    "rest_framework",       # Django REST Framework - 构建 API
    "corsheaders",          # 跨域支持
    # ===== 自定义应用 =====
    "players",              # 玩家管理模块
    "mails",                # 邮件补偿模块
    "notices",              # 全服公告模块
]

# ============================================
# 🔗 Middleware - 中间件配置
# ============================================

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",  # ⚠️ 必须放在最前面！
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "my_gm_backend.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "my_gm_backend.wsgi.application"


# ============================================
# 🗄️ Database - 数据库配置 (PostgreSQL)
# ============================================

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",  # 使用 PostgreSQL
        "NAME": "gm_system",        # 数据库名（需要先在 PostgreSQL 中创建）
        "USER": "postgres",         # 用户名
        "PASSWORD": "123456",       # 密码
        "HOST": "localhost",        # Docker 映射到本地
        "PORT": "5432",             # PostgreSQL 默认端口
    }
}


# ============================================
# 🌐 CORS - 跨域配置
# ============================================

# 开发环境：允许所有来源（生产环境请改为具体域名）
CORS_ALLOW_ALL_ORIGINS = True

# 如果需要携带 Cookie，取消下面注释：
# CORS_ALLOW_CREDENTIALS = True


# ============================================
# 🔌 REST Framework - API 配置
# ============================================

REST_FRAMEWORK = {
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.AllowAny",  # 开发阶段允许所有请求
    ],
    "DEFAULT_RENDERER_CLASSES": [
        "rest_framework.renderers.JSONRenderer",
    ],
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# ============================================
# 🌍 Internationalization - 国际化配置
# ============================================

LANGUAGE_CODE = "zh-hans"  # 中文简体

TIME_ZONE = "Asia/Shanghai"  # 中国时区

USE_I18N = True

USE_TZ = True


# ============================================
# 📁 Static files - 静态文件
# ============================================

STATIC_URL = "static/"

# Default primary key field type
DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"
