# Generated by Django 6.0 on 2025-12-28 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Notice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100, verbose_name="公告标题")),
                ("content", models.TextField(verbose_name="公告内容")),
                (
                    "notice_type",
                    models.CharField(
                        choices=[
                            ("login", "登录公告"),
                            ("marquee", "滚动跑马灯"),
                            ("system", "系统邮件通知"),
                        ],
                        default="login",
                        max_length=20,
                        verbose_name="公告类型",
                    ),
                ),
                (
                    "priority",
                    models.IntegerField(
                        default=0,
                        help_text="数值越大，前端展示时越靠前",
                        verbose_name="优先级",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("draft", "草稿"), ("published", "已发布")],
                        default="draft",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                (
                    "start_time",
                    models.DateTimeField(
                        help_text="公告开始展示的时间", verbose_name="生效时间"
                    ),
                ),
                (
                    "end_time",
                    models.DateTimeField(
                        help_text="公告停止展示的时间", verbose_name="失效时间"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
            ],
            options={
                "verbose_name": "公告",
                "verbose_name_plural": "公告列表",
                "db_table": "notices",
                "ordering": ["-priority", "-created_at"],
            },
        ),
    ]
