# Generated by Django 6.0 on 2025-12-31 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notices", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notice",
            name="end_time",
            field=models.DateTimeField(
                db_index=True, help_text="公告停止展示的时间", verbose_name="失效时间"
            ),
        ),
        migrations.AlterField(
            model_name="notice",
            name="start_time",
            field=models.DateTimeField(
                db_index=True, help_text="公告开始展示的时间", verbose_name="生效时间"
            ),
        ),
        migrations.AlterField(
            model_name="notice",
            name="status",
            field=models.CharField(
                choices=[("draft", "草稿"), ("published", "已发布")],
                db_index=True,
                default="draft",
                max_length=20,
                verbose_name="状态",
            ),
        ),
    ]
