# Generated by Django 6.0 on 2025-12-20 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Player",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "username",
                    models.CharField(max_length=50, unique=True, verbose_name="玩家名"),
                ),
                ("level", models.IntegerField(default=1, verbose_name="等级")),
                ("gold", models.IntegerField(default=0, verbose_name="金币")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="注册时间"),
                ),
            ],
            options={
                "verbose_name": "玩家信息",
                "verbose_name_plural": "玩家信息",
            },
        ),
    ]
