# Generated by Django 6.0 on 2025-12-22 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game_core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="项目名称")),
                ("logo_text", models.CharField(default="XD", max_length=5)),
                ("logo_color", models.CharField(default="#0075ff", max_length=20)),
                (
                    "budget",
                    models.CharField(default="$0", max_length=50, verbose_name="预算"),
                ),
                ("completion", models.IntegerField(default=0, verbose_name="完成度")),
            ],
            options={
                "verbose_name": "项目管理",
                "verbose_name_plural": "项目管理",
            },
        ),
        migrations.DeleteModel(
            name="Player",
        ),
    ]
