# Generated by Django 6.0 on 2025-12-27 13:43

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Player",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="玩家ID",
                    ),
                ),
                ("nickname", models.CharField(max_length=50, verbose_name="昵称")),
                ("level", models.PositiveIntegerField(default=1, verbose_name="等级")),
                ("gold", models.BigIntegerField(default=0, verbose_name="金币")),
                ("diamond", models.BigIntegerField(default=0, verbose_name="钻石")),
                (
                    "status",
                    models.CharField(
                        choices=[("normal", "正常"), ("banned", "封禁")],
                        default="normal",
                        max_length=10,
                        verbose_name="账号状态",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="注册时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="最后更新时间"),
                ),
            ],
            options={
                "verbose_name": "玩家",
                "verbose_name_plural": "玩家列表",
                "db_table": "players",
                "ordering": ["-created_at"],
            },
        ),
    ]
