# Generated by Django 6.0 on 2025-12-31 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("players", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="player",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, db_index=True, verbose_name="注册时间"
            ),
        ),
        migrations.AlterField(
            model_name="player",
            name="nickname",
            field=models.CharField(db_index=True, max_length=50, verbose_name="昵称"),
        ),
        migrations.AlterField(
            model_name="player",
            name="status",
            field=models.CharField(
                choices=[("normal", "正常"), ("banned", "封禁")],
                db_index=True,
                default="normal",
                max_length=10,
                verbose_name="账号状态",
            ),
        ),
    ]
