# Generated by Django 5.2.8 on 2026-01-04 09:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('players', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CDK',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, help_text='唯一兑换码，如 KURO666', max_length=50, unique=True, verbose_name='兑换码')),
                ('item_id', models.IntegerField(default=1, help_text='1=金币, 2=钻石', verbose_name='道具ID')),
                ('item_count', models.PositiveIntegerField(default=100, verbose_name='道具数量')),
                ('max_uses', models.PositiveIntegerField(default=1, help_text='最多可被兑换次数', verbose_name='总额度')),
                ('used_count', models.PositiveIntegerField(default=0, verbose_name='已使用次数')),
                ('expires_at', models.DateTimeField(db_index=True, verbose_name='过期时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': 'CDK兑换码',
                'verbose_name_plural': 'CDK兑换码列表',
                'db_table': 'cdks',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CDKLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('redeemed_at', models.DateTimeField(auto_now_add=True, verbose_name='兑换时间')),
                ('cdk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='redeem_logs', to='cdks.cdk', verbose_name='兑换码')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cdk_logs', to='players.player', verbose_name='玩家')),
            ],
            options={
                'verbose_name': 'CDK兑换记录',
                'verbose_name_plural': 'CDK兑换记录',
                'db_table': 'cdk_logs',
                'ordering': ['-redeemed_at'],
                'unique_together': {('player', 'cdk')},
            },
        ),
    ]
