# Generated by Django 6.0 on 2025-12-31 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cdks", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cdk",
            name="code",
            field=models.CharField(
                db_index=True,
                help_text="唯一兑换码，如 KURO666",
                max_length=50,
                unique=True,
                verbose_name="兑换码",
            ),
        ),
        migrations.AlterField(
            model_name="cdk",
            name="expires_at",
            field=models.DateTimeField(db_index=True, verbose_name="过期时间"),
        ),
    ]
