# Generated by Django 6.0 on 2025-12-28 03:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        help_text="如: 创建、修改、删除、发放邮件、封禁玩家",
                        max_length=50,
                        verbose_name="操作类型",
                    ),
                ),
                (
                    "app_label",
                    models.CharField(
                        help_text="如: players, mails, cdks",
                        max_length=50,
                        verbose_name="应用模块",
                    ),
                ),
                (
                    "model_name",
                    models.CharField(
                        help_text="如: Player, Mail, CDK",
                        max_length=50,
                        verbose_name="模型名称",
                    ),
                ),
                (
                    "target",
                    models.CharField(
                        help_text='如: 玩家 "小明"',
                        max_length=200,
                        verbose_name="被操作对象",
                    ),
                ),
                (
                    "details",
                    models.TextField(
                        blank=True,
                        help_text="如: 金币从 100 变为 1000",
                        verbose_name="详细改动",
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="IP地址"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="操作时间"),
                ),
                (
                    "admin",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_logs",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="操作管理员",
                    ),
                ),
            ],
            options={
                "verbose_name": "审计日志",
                "verbose_name_plural": "审计日志",
                "db_table": "audit_logs",
                "ordering": ["-created_at"],
            },
        ),
    ]
